name: home_info_point_client
description: Dart client for fetching and interpreting data from the Home.InfoPoint web service.
version: 1.0.0
repository: https://github.com/Venatrixx/home_info_point_client

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.4.0
  html: ^0.15.6
  

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
